Td:
- co
- jak
- kdo
- čem
- čím
- čeho
- proč
- jaká
- kolik
- kde
- jakých
- které
- kdy
- jaký
- vlastně
- jaké
- čemu
- jakou
- koho
- oč
- nač
Tu:
- mi
- jste
- ten
- má
- pokud
- víte
- slyšíš
- to
- není
- vám
- bylo
- takže
- připouštíte
- dá
- jsi
- mu
- mohou
- už
- mohl
- opravdu
- existují
- může
- lze
- že
- pro
- mě
- ti
- vy
- máme
- ví
- ještě
- měl
- jde
- budeme
- existuje
- ty
- pomohou
- vůbec
- fakt
- mám
- máte
- máš
- hrozí
- vás
- snad
- chtěl
- tam
- mít
- cítíte
- teď
- nebo
- mají
- něco
- dáte
- za
- můžeme
- někdo
- nic
- chceš
- 'no'
- myslíte
- své
- i
- víš
- váš
- já
- také
- jeho
- tady
- blíží
- počkejte
- konec
- znamená
- měli
- jestli
- být
- platí
- po
- nová
- tohle
- bez
- václava
- vášniví
- euro
- reforma
- můžu
- cítíš
- vydrží
- ano
- nevíš
- děláš
- či
- myslíš
- poněkud
- dokážete
- ve
- skutečně
- jo
- mohla
