Td:
- wie
- wo
- viele
- was
- schnell
- welche
- woher
- wer
- viel
- welcher
- wann
- kommst
- konnte
- warum
- wohin
- wievielmal
- lange
- oft
- welchen
- bis
- womit
- welchem
- wem
- wen
- worüber
- genau
- führt
- denkst
- mit
- finde
- um
- bier
- wieso
- groß
- spielt
- bedeutet
Tu:
- ich
- du
- oder
- können
- sie
- die
- es
- das
- magst
- der
- gibt
- also
- ein
- da
- wir
- darf
- bist
- haben
- dieser
- verstehst
- kannst
- könnten
- warst
- vielleicht
- man
- sich
- ob
- muss
- kennen
- dir
- eine
- er
- wirst
- ihr
- auch
- bekommt
- hier
- nehmen
- wollt
- kennst
- jemand
- als
