Td:
- how
- long
- which
- why
- where
- what
- what's
- time
- who
- much
- one
- when
- and
- old
- many
- your
- else
- often
- kind
- 'on'
- for
- who's
- so
- by
- whose
- where's
- more
- fast
- how's
- exactly
- told
Tu:
- could
- we
- he
- you
- this
- it
- can
- i
- isn't
- have
- may
- there
- they
- a
- any
- she
- as
- 'yes'
- don't
- can't
- must
