Td:
- and
- but
- how
- so
- why
- what
- what's
- when
- where
- which
- who
- who's
- whose
Tu:
- am
- are
- can
- could
- did
- do
- does
- don't
- have
- is
- isn't
- may
- or
- shall
- will
- would
- you
