Td:
- qué
- cuál
- dónde
- adónde
- cuándo
- quién
- cuánto
- cómo
- desde
- dura
- tiempo
- o
- fue
- tipo
- bajo
- color
- cuesta
- dinero
- cuántas
- cuáles
- cuántos
- llegamos
Tu:
- usted
- tienes
- 'no'
- me
- puede
- que
- puedes
- podemos
- ir
- tengo
- posible
- hay
- un
- sabes
- el
- hablar
- algún
- tienen
- sentarnos
- una
- nos
- dejar
- has
- algunas
- eso
- podrías
- todavía
- algo
- los
- ya
- podría
- venir
- entiendes
- tiene
- visto
- lleva
- alquilar
- este
- también
- él
- habéis
- hacer
- libre
- necesito
- hacerlo
- bien
- pedir
- alguien
- estado
- favor
- tenemos
- encender
- podríamos
- alguna
- alquilan
- he
