Td:
- kde
- kam
- odkud
- kdy
- dokdy
- odkdy
- jak
- kdo
- koho
- komu
- koho
- kom
- kým
- co
- čeho
- čemu
- co
- oč
- čem
- čím
- jaký
- jaká
- jaké
- jací
- jakého
- jakých
- jakému
- jakého
- jakou
- jakém
- jakým
- který
- která
- které
- kteří
- kterého
- kterých
- kterému
- kterého
- kterém
- kterým
- čí
- kolik
- proč
- where
- where
- when/what time
- how
- how's
- who
- who's
- whose
- who's
- whom
- what
- what's
- why
- why's
- which
- when
- when's
- wer
- wessen
- wem
- wen
- was
- wie
- wann
- wieso
- welche
- welcher
- welches
- welchen
- welchem
- warum
- wieviel
- wieviele
- wievielmal
- wievielter
- wievieltes
- worum
- worüber
Tu:
- mám
- máš
- má
- máme
- máte
- mají
- jsem
- jsi
- je
- jsou
- jste
- můžu
- mohu
- můžeš
- může
- můžeme
- můžete
- můžou
- do
- does
- don't
- doesn't
- did
- didn't
- are
- is
- am
- aren't
- isn't
- was
- were
- will
- would
- could
- shall
- have
- has
- haven't
- hasn't
- had
- habe
- hast
- hat
- haben
- habt
- bin
- ist
- sind
- seid
- sind
- werde
- wirst
- wird
- werden
- werdet
- werden
- will
- willst
- will
- wollen
- wollt
- mag
- magst
- mögen
- mögt
- mochte
- mochtest
- mochten
- mochtet
- kann
- kannst
- kann
- können
- könnt
-
