Td:
- kde
- kam
- odkud
- kdy
- dokdy
- odkdy
- jak
- kdo
- koho
- komu
- koho
- kom
- kým
- co
- čeho
- čemu
- co
- oč
- čem
- čím
- jaký
- jaká
- jaké
- jací
- jakého
- jakých
- jakému
- jakého
- jakou
- jakém
- jakým
- který
- která
- které
- kteří
- kterého
- kterých
- kterému
- kterého
- kterém
- kterým
- čí
- kolik
- proč
Tu:
- mám
- máš
- má
- máme
- máte
- mají
- jsem
- jsi
- je
- jsou
- jste
- můžu
- mohu
- můžeš
- může
- můžeme
- můžete
- můžou
