Td:
- where
- how
- who
- what
- why
- when
- which
- whose
- whom
- where's
- how's
- who's
- what's
- why's
- when's
Tu:
- do
- does
- did
- are
- is
- am
- was
- were
- will
- would
- can
- could
- shall
- may
- have
- has
- had
- don't
- doesn't
- didn't
- aren't
- wasn't
- weren't
- isn't
- can't
- wouldn't
- couldn't
- haven't
- hasn't
- hadn't