Td:
- wer
- wessen
- wem
- wen
- was
- wie
- wann
- wieso
- welche
- welcher
- welches
- welchen
- welchem
- warum
- wieviel
- wieviele
- wievielmal
- wievielter
- wievieltes
- wo
- wofür
- woher
- wohin
- womit
- wonach
- worauf
- woran
- worin
- worum
- worüber
- wovon
- wozu
Tu:
- habe
- hast
- hat
- haben
- habt
- bin
- ist
- sind
- seid
- sind
- werde
- wirst
- wird
- werden
- werdet
- werden
- will
- willst
- will
- wollen
- wollt
- mag
- magst
- mögen
- mögt
- mochte
- mochtest
- mochten
- mochtet
- kann
- kannst
- kann
- können
- könnt
