Td:
- where
- where
- when/what time
- how
- how's
- who
- who's
- whose
- who's
- whom
- what
- what's
- why
- why's
- which
- when
- when's
Tu:
- do
- does
- don't
- doesn't
- did
- didn't
- are
- is
- am
- aren't
- isn't
- was
- were
- will
- would
- could
- shall
- have
- has
- haven't
- hasn't
- had
