Td:
- что
- откуда
- где
- чему
- сколько
- как
- кто
- чего
- куда
- интересно
- времени
- когда
- долго
- почему
- чем
- каков
- раз
- каком
- чём
- кем
- который
- какой
- итак
- зачем
- какое
- какую
- какие
- находится
- называется
- казалось
- расскажите
- каким
- кому
- какая
- кого
- ближайший
- избежать
- при
- какого
- чья
- какому
- ждёт
- каковы
- спросите
- какова
- чьё
- часто
- каких
- чей
- котором
- именно
- чёрт
- делать
- помочь
- были
Tu:
- выходит
- ведь
- быть
- может
- не
- есть
- могу
- можно
- говорите
- ли
- было
- много
- можете
- разве
- вдруг
- оставить
- могли
- будешь
- вас
- знаешь
- русский
- туда
- можешь
- говорить
- умеешь
- пойдём
- уже
- такой
- наверное
- россии
- будут
- знаете
- нужен
- что-нибудь
- хорошо
- хотите
- возможно
- те
- должен
- ради
- попросить
- представляете
- хочешь
- то
- неужели
- меня
- понимаете
- опять
- только
- время
- нужно
- идёт
- надо
- всех
- чтобы
- все
- понял
- тоже
- любите
- кто-нибудь
- этот
- видели
- сесть
- без
- нужна
- получается
- ваш
- идеал
- была
- боишься
- можем
- скажете
- помните
