Td:
- jak
- kdo
- čím
- proč
- jaká
- kolik
- kdy
- jaký
- vlastně
- jaké
Tu:
- mi
- ten
- víte
- není
- vám
- jsi
- mu
- mohou
- už
- lze
- že
- pro
- ti
- vy
- máme
- ještě
- měl
- existuje
- ty
- snad
- tam
- cítíte
- nebo
- za
- chceš
- víš
- být
- můžu
