dataset:
  devel_tsv: EN/valid.txt
  loader:
    devel_samples: 1000
    input_size: 1024
    min_batch_size: 2
    output_size: 1024
    shuffle_window: 1000
  test_tsv: EN/test.txt
  train_tsv: EN/train.txt
evaluation:
  metric: match
predict:
  batch_size: 20
  max_input_length: 512
  max_output_length: 768
t5_model:
  load_checkpoint: EN/e0
  pre_trained: t5-base
  save_checkpoint: EN/e0
  save_checkpoint_every: 1
tokenizer:
  spm: modely/T5_32k_CCen.model
training:
  encoder_trainable: true
  initial_epoch: 10
  learning_rate: 0.01
  learning_rate_schedule: true
  n_epochs: 10
  shared_trainable: false
  skip_samples: 1092254
  steps_per_epoch: 1000
